### acessando via get
GET http://localhost:3000/subscribers
###
POST http://localhost:3000/subscribers
Content-Type: application/json
{
    "userName": "Arthur Vincius",
    "userChannel": "Curso em Vídeo"
}
###
POST http://localhost:3000/subscribers
Content-Type: application/json
{
    "userName": "Beatriz Helena",
    "userChannel": "Manual do Mundo"
}
###
GET http://localhost:3000/subscribers/6197e053a69fec6d9eb1b834
###
DELETE http://localhost:3000/subscribers/6197e853822a90b5df8b7dd6
###
PATCH  http://localhost:3000/subscribers/6197e13ca69fec6d9eb1b839
Content-Type: application/json
{
    "userName": "Ibere Tenório",
}
###